management:
  metrics:
    export:
      wavefront:
        api-token: ${WAVEFRONT_TOKEN}
        uri: https://vmware.wavefront.com
  endpoints:
    web:
      exposure:
        include: "*"
wavefront:
  application:
    name: mark-douglass-spring-sample
    service: mark-douglass-spring-sample-service