management:
  metrics:
    export:
      wavefront:
        api-token: f28e249b-156e-420c-803c-07fc48af5d26
        uri: https://vmware.wavefront.com
  endpoints:
    web:
      exposure:
        include: "*"
wavefront:
  application:
    name: mark-douglass-spring-sample
    service: mark-douglass-spring-sample-service